import { type NextPage } from "next";
import Head from "next/head";
import AppShellDemo from "@Components/Shell";
const SiteInfo: NextPage = () => {
  return (
    <>
      <Head>
        <title>Site info Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Hello site info</h1>
    </>
  );
};

export default SiteInfo;